name: weight_tracker
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
  numberpicker: ^0.1.6
  firebase_auth: ^0.5.19
  firebase_database: ^1.0.4
  firebase_analytics: ^1.0.3
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  tuple: ^1.0.2
  intl: ^0.15.7
  shared_preferences: ^0.4.2
  mockito: 3.0.0 #https://github.com/dart-lang/mockito/issues/172
  google_sign_in: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
  - assets/scale-bathroom.png
  - assets/user.png
  - assets/google.png
